apiVersion: v1
kind: Service
metadata:
  name: app4-service
spec:
  selector:
    app: app4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort   # or LoadBalancer if supported
