# name: Build and Push Docker

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   docker:
#     runs-on: [self-hosted] 

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           logout: false
       
#       - name: Build & Push App1
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/app1:latest ./app1
#           docker push ${{ secrets.DOCKER_USERNAME }}/app1:latest

#       - name: Build & Push App2
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/app2:latest ./app2
#           docker push ${{ secrets.DOCKER_USERNAME }}/app2:latest
