name: Build and Push Docker Images (Self-Hosted)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    # Specify self-hosted runner
    runs-on: [self-hosted]

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build and push app1
      - name: Build & Push App1
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app1:latest ./app1
          docker push ${{ secrets.DOCKER_USERNAME }}/app1:latest

      # # 4️⃣ Build and push app2
      # - name: Build & Push App2
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/app2:latest ./app2
      #     docker push ${{ secrets.DOCKER_USERNAME }}/app2:latest
